# Generating  the Dataset

In [1]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

In [2]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

# Reading the Dataset 

In [5]:
def load_array(data_arrays, batch_size, is_train=True):
    # construct a tensorflow data iterator
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        datast = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

In [6]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [7]:
next(iter(data_iter))

(<tf.Tensor: id=41, shape=(10, 2), dtype=float32, numpy=
 array([[ 1.36823595e+00,  2.36078396e-01],
        [ 1.02169919e+00, -1.39640534e+00],
        [ 1.61359280e-01, -1.91782331e+00],
        [-1.80548263e+00, -3.11860412e-01],
        [-5.80118775e-01,  1.85919154e+00],
        [ 4.42854702e-01,  1.04741946e-01],
        [ 5.22062719e-01, -3.67527783e-01],
        [ 4.21752751e-01, -1.34950832e-01],
        [-1.51198760e-01,  2.26671004e+00],
        [-4.40784439e-04, -1.60294533e+00]], dtype=float32)>,
 <tf.Tensor: id=42, shape=(10, 1), dtype=float32, numpy=
 array([[ 6.149515 ],
        [10.995129 ],
        [11.046111 ],
        [ 1.641127 ],
        [-3.2802238],
        [ 4.74     ],
        [ 6.487624 ],
        [ 5.5077667],
        [-3.809421 ],
        [ 9.63156  ]], dtype=float32)>)

# Defining the Model 

In [8]:
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

# Initializing Model Parameters 

In [9]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

# Defining Loss Function 

In [10]:
loss = tf.keras.losses.MeanSquaredError()

# Defining Optimization Algorithm 

In [11]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

# Training 

In [13]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 32.768257
epoch 2, loss 32.768257
epoch 3, loss 32.768257


In [15]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([ 1.9987835 -3.4024074], shape=(2,), dtype=float32)
error in estimating b [4.2]
